### ISSUE TITLE
example code has a runtime exception: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by winglight** [samschott/desktop-notifier#10]
* Desktop Notifier version: latest
* Python version: 3.8
* Operating System: macOS 15 m1

### Description
example code
```
import asyncio
from desktop_notifier import DesktopNotifier

notify = DesktopNotifier()

async def main():
    n = await notify.send(title="Hello world!", message="Sent from Python")

    await notify.clear(n)  # removes the notification
    await notify.clear_all()  # removes all notifications for this app

asyncio.run(main())
```
run python ./notify.py 
```
  File "./notify.py", line 6
    async def main():
            ^
SyntaxError: invalid syntax
```

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by winglight** [comment]
> Are you sure that you are running the code with Python 3.8? AFAIK, `python` on macOS defaults to Python 2.7 which whereas `python3` should run Python 3.8 or Python 3.9.

Yes, I run it in anaconda with python 3.8. And it's python 3.9 as the default version since I bought this mba m1.

**Comment by SamSchott** [comment]
Strange, the example runs perfectly fine for me 🤷

You might not see any notifications when running with Anaconda Python (see https://github.com/SamSchott/desktop-notifier#notes-on-macos) but there should not be any SyntaxErrors.
