### ISSUE TITLE
pytest freezes after first notification test on macOS

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [samschott/desktop-notifier#152]
* Desktop Notifier version: `5.0.0` (current master)
* Python version: `3.12.4`
* Operating System: macOS 13.6.7 (Ventura)

### Description
Tried running bare `pytest` and it freezes after sending a single notification ("The world is yours!") to the desktop. Not sure if that's the first test but it's definitely only one message. In the frozen state I cannot `ctrl-c` or `ctrl-d` my way out; only killing the process from another window returns me to shell.

Odd because `pytest` used to work fine for me with version 4.x.

### What I Did

```
(.venv)$ pytest
================================================================================= test session starts =================================================================================
platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /Users/uzor/lib_repos/desktop-notifier
configfile: pyproject.toml
plugins: cov-5.0.0, asyncio-0.23.7
asyncio: mode=Mode.STRICT
collecting ... ^C^C^C^C^C^C^C^D
```

**Comment by samschott** [comment]
Are you running the tests in the `tests/` directory of this repo, or something else?

**Comment by michelcrypt4d4mus** [comment]
lol you're right, my bad... i had a local file with `test_` in the filename that was triggering instead of the real tests. my bad!
