### ISSUE TITLE
Clarify units for timeout parameter

### ISSUE THREAD

**Issue by slacksystem** [samschott/desktop-notifier#179]
* Desktop Notifier version: 5.0.1
* Python version: 3.12
* Operating System: Linux (Nobara)

### Description

Not sure how to follow the template given here as this is a question and suggestion, hope that's ok!

The documentation doesn't list the units for the `timeout` parameters and attributes. I could see it being seconds or milliseconds (or something else?). I think even if the answer may be obvious to some, it's good practice to add units to time or physical parameters. I'd be open to submitting a PR with edited docstrings if that's something you'd likely accept.

**Comment by samschott** [comment]
It's in seconds. A PR to improve the doc strings would be very welcome!

**Comment by slacksystem** [comment]
Fixed by #180.
