### ISSUE TITLE
Callback 'on_dismissed' doesn't work on ventura ?

### ISSUE THREAD

**Issue by khurshid-alam** [samschott/desktop-notifier#185]
* Desktop Notifier version: 5.0.1
* Python version: 3.12
* Operating System: MacOS Ventura

### Description

I am planning to use this in a script. With following condition

- The notifications performs a action when clicked.

- The Script must exit after notification has been clicked or dismissed.

### What I Did

```py
import os
import sys
import asyncio
import datetime
import functools


from rubicon.objc.eventloop import EventLoopPolicy

# Install the event loop policy
asyncio.set_event_loop_policy(EventLoopPolicy())


from desktop_notifier import DesktopNotifier, Urgency, Button, ReplyField, DEFAULT_SOUND

notifier = DesktopNotifier()



#print (notifier.get_capabilities())



async def waiter(event):
	def fp():
		print ("Ack")
		#os.system("open -a Terminal")
		event.set()

	print('waiting for notification to be clicked or dismissed...')
	await notifier.send(
		title="Julius Caesar",
		message="Et tu, Brute?",
		urgency=Urgency.Normal,
		on_clicked=functools.partial(fp),
		on_dismissed=functools.partial(fp),
		sound=DEFAULT_SOUND,
	)


	await event.wait()



	print('.....Notification has been clicked!')


async def main():
	# Create an Event object.
	event = asyncio.Event()
	
	# Spawn a Task to wait until 'event' is set.
	waiter_task = asyncio.create_task(waiter(event))
	
	# Wait until the waiter task is finished.
	await waiter_task

asyncio.run(main())
```

This works fine with `on_clicked`. But when I closed the notification by clicking cross button, it doesn't work. Any idea why ?

----
[macOS_notification](https://github.com/Jorricks/macos-notifications) has something like this which stops the loop when every notification handled.

```
    while client.get_notification_manager().get_active_running_notifications() > 0:
        time.sleep(1)
    client.stop_listening_for_callbacks()
```

I wish if we could do something similar here. I tried with 

```
	while len(notifier.current_notifications) < 1:
                await Asyncio.sleep(1)
		event.set()
```

But didn't work.

**Comment by samschott** [comment]
I think you are seeing a bug in the currently released version. Could you try with the prerelease 6.0.0.dev0? You can install it with:

```
pip3 install -U --pre desktop-notifier
```

**Comment by khurshid-alam** [comment]
@samschott Yes, I have checked. It works with **6.0.0.dev0**. Thanks.
