### ISSUE TITLE
Allow setting custom notifications sounds

### ISSUE THREAD

**Issue by samschott** [samschott/desktop-notifier#2]
**Is your feature request related to a problem? Please describe.**
Currently, there is only support for turning notification sounds off (default) or on. When enabled, the platform's default sound for notifications will be used, if available. It would be nice to support custom sounds.

**Describe the solution you'd like**
Ideally, we would allow specifying either:

1) an identifier for a platform-provided sound
2) the path to a sound file

Both options will require some abstraction over platform differences: macOS only provides two notification sounds, default and critical, and critical alerts require a special entitlement issued by Apple. Linux desktops typically allow using all platforms sounds from the [sound-theme-spec](https://www.freedesktop.org/wiki/Specifications/sound-theme-spec/). Both platforms allow specifying sound files but supported audio formats will be limited. In addition, macOS requires the sound file to be stored either in the app bundle or in the `/Library/Sounds` directory of the app's container directory (see the [UNNotificationSound docs](https://developer.apple.com/documentation/usernotifications/unnotificationsound?language=objc)). It therefore appears that custom sound files are only support from bundled apps.

**Describe alternatives you've considered**
Keep the sound option as is: default or nothing.

**Comment by michelcrypt4d4mus** [comment]
this seems like it can be closed?

**Comment by samschott** [comment]
Indeed, thanks for flagging!
