### ISSUE TITLE
weak docs and tutorials and custom sound !

### ISSUE THREAD

**Issue by matin1099** [samschott/desktop-notifier#32]
* Desktop Notifier version:3.4.0
* Python version:3.10
* Operating System:Linux Debian distros , Arch , MS Win 8.1 & 10 & 11,  Mac OS 10 & 12

### Description
Hi, thanks for your hard workings.

in my office we use this library to create 2 necessary softwares one: to alert us  extracting  price list has done and the other: urgent sell has been issued.

for our developers, lack of docs and tutorials are pain. To be honest ,apologize my French!, a saw in our asses! not gonna lie!!

and for for sounds:
 with this in mind this library play a vital role in my department having a same sound for 2 different software is not good.better to be able to use custome sounds

p.s. : all OS above are using in my office!

**Comment by samschott** [comment]
Hi @matin1099, glad to hear that you find this project useful.

Regarding the docs, which parts in particular do you find confusing or lacking? The docs for the public API, or rather platform-specific support of features? If you find particular parts could use some improvement, any contributions are more then welcome!

Regarding supporting custom sounds, I'll need to look into platform support first and see if I can find a reasonable abstraction that works for all platforms.

**Comment by matin1099** [comment]
Hi again.
we have 5 python developers:1 senior ,2 junior ,2 intern.
The only person find how this project works was the senior! after 12-13 hour of reading codes!! 

to be honest, this project is unique and cool; I'm  sure  a minimal docs will be great!

unfortunately our we can't help contribute in this project as DTWDG. but an individual , I will introduce this proj to someones with open times and interests!

with loves and peace for everyone

**Comment by michelcrypt4d4mus** [comment]
custom sounds are now available with the release of version 5.0. @samschott maybe it's time to close this issue?

**Comment by samschott** [comment]
Indeed, thanks for flagging!

Feel free to open a separate issue for specific documentation improvements you'd like to see.
