### ISSUE TITLE
OSError on Windows

### ISSUE THREAD

**Issue by ilkergzlkkr** [samschott/desktop-notifier#41]
* Desktop Notifier version: 3.4.1
* Python version: Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
* Operating System: Windows 10 Pro 21H2 19044.2130
* Virtualenv: packages: pip==22.2.2, setuptools==65.3.0, wheel==0.37.1

```console
$ pip freeze
desktop-notifier==3.4.1
packaging==21.3
pyparsing==3.0.9
winsdk==1.0.0b7
```

### What I Did

I tried to run [basic example](https://github.com/samschott/desktop-notifier/blob/master/README.md#usage) on README

### Result

```console
Traceback (most recent call last):
  File "C:\Users\ilker\Desktop\dev\env-trash\desktop-notifier\main.py", line 4, in <module>
    notifier = DesktopNotifier()
  File "C:\Users\ilker\Desktop\dev\env-trash\desktop-notifier\venv\lib\site-packages\desktop_notifier\main.py", line 161, in __init__
    self._impl = impl_cls(app_name, app_icon, notification_limit)
  File "C:\Users\ilker\Desktop\dev\env-trash\desktop-notifier\venv\lib\site-packages\desktop_notifier\winrt.py", line 74, in __init__
    self.notifier = self.manager.create_toast_notifier(self._appid)
OSError: [WinError -2147024809] Parametre hatalı
```
Parametre hatalı -> The parameter is incorrect (in english)

**Comment by samschott** [comment]
Thanks for the report. I no longer have access to a Windows VM, after switching to an Apple Silicon mac, so this will be difficult for me to reproduce or fix. If you are able to contribute a fix, this would be very much appreciated!

As a pointer, the windows backend gets the app ID directly from `CoreApplication`:

https://github.com/samschott/desktop-notifier/blob/adebc84094291bc170118540fc86dc6b3c48e70f/src/desktop_notifier/winrt.py#L72-L74

The documentation for `ToastNotificationManager` is available at https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotificationmanager/

**Comment by iamkroot** [comment]
Looks like a general Windows bug. One of my users also got this- https://github.com/iamkroot/trakt-scrobbler/issues/224

Will try to debug in Windows if I get some time.

**Comment by samschott** [comment]
Looks like the winrt API changed slightly during the last couple of release (it is still in beta, so I don't blame them).

I've made adjustments accordingly and released v3.4.2.dev0 of `desktop-notifier`. Could you see if this fixes this issue?

**Comment by ilkergzlkkr** [comment]
Sorry for being late to reply.
Using v3.4.2.dev0, i still get the `OSError: [WinError -2147024809]`

Is there any way to use `Github Actions Workflow` to check windows is being able to run the example code in repo.

**Comment by ilkergzlkkr** [comment]
`CoreApplication.get_id()` does not work, AppId is always nonestr (`self._appid=''`)
While i was searching, found this: https://github.com/pywinrt/python-winsdk/issues/2

- i tried to hardcode `self._appid` as `'hi'`
- resulted as error in `BackgroundTaskRegistration.get_all_tasks()`
```console
Notification failed
Traceback (most recent call last):
  File "C:\Users\ilker\Desktop\dev\env-trash\desktop-notifier\venv\lib\site-packages\desktop_notifier\base.py", line 207, in send
    platform_nid = await self._send(notification, notification_to_replace)
  File "C:\Users\ilker\Desktop\dev\env-trash\desktop-notifier\venv\lib\site-packages\desktop_notifier\winrt.py", line 128, in _send
    await self._request_background_task_access()
  File "C:\Users\ilker\Desktop\dev\env-trash\desktop-notifier\venv\lib\site-packages\desktop_notifier\winrt.py", line 97, in _request_background_task_access
    tasks = BackgroundTaskRegistration.get_all_tasks()
OSError: [WinError -2147023728] Eleman bulunamadı ((Child not found in english))
```
- removed the request access block https://github.com/samschott/desktop-notifier/blob/adebc84094291bc170118540fc86dc6b3c48e70f/src/desktop_notifier/winrt.py#L101-L103
- now i have no exceptions but no toast notification on my windows either...
- so i found the hacky id in another repo [(code)](https://github.com/DatGuy1/Windows-Toasts/blob/cf632f818a061b2463ad30b34488470609254622/src/windows_toasts/windows_toasts.py#L102) [(repo)](https://github.com/DatGuy1/Windows-Toasts)

**Now it works!** 😊👌
![image](https://user-images.githubusercontent.com/25375335/202277985-1cccf716-2760-48a3-b2d9-aaa71c424103.png)

Note: I also used the basic notification toast with [hacky](https://github.com/DatGuy1/Windows-Toasts/blob/cf632f818a061b2463ad30b34488470609254622/src/windows_toasts/windows_toasts.py#L102) id and any string values
```py
# using hacky _appid
await notifier.send(
        title="Julius Caesar",
        message="Et tu, Brute?",
    )
 ```
I had to use the hacky id to run the toast. This is the only way i can get it work.

**Comment by samschott** [comment]
Ah, I see, you are practically impersonating another app to show notifications.

I expect that Windows has similar policies as macOS around only allowing proper "applications" to send desktop notifications, but with a lot weaker enforcement of those policies.

How did you install Python? When using the official installer from [python.org](https://www.python.org), it should behave properly with an App ID of "Python". Likewise, if you use `desktop-notifier` from a proper proper app, created for example with pyinstaller or briefcase, it just also just work.

This error should definitely be handled more gracefully with a better error message so that users understand what is going on.

**Comment by ilkergzlkkr** [comment]
I used python.org for windows indeed. I am using Virtualenv, may be that is the case idk.

**Comment by jaydeepjondhale** [comment]
i'm getting the same issue on the latest version(3.4.2).

**Comment by iamkroot** [comment]
@samschott 
I'm not sure if the issue is fixed yet. Simply trying to run an app causes a crash-

```
OSError

[WinError -2147024809] The parameter is incorrect

at .local\pipx\venvs\trakt-scrobbler\Lib\site-packages\desktop_notifier\winrt.py:74 in init
70│ ) -> None:
71│ super().init(app_name, app_icon, notification_limit)
72│ self._appid = CoreApplication.get_id()
73│ self.manager = ToastNotificationManager.get_default()
→ 74│ self.notifier = self.manager.create_toast_notifier(self._appid)
75│
76│ # BackgroundExecutionManager.remove_access(self._appid)
77│ # CoreApplication.add_background_activated(self._on_background_activated)
78│
```

To repro, `pipx install trakt-scrobbler` followed by `trakts init` on Windows.

**Comment by samschott** [comment]
Darn, looks like this was a stupid oversight of me.
