### ISSUE TITLE
[macOS] Add support for "open URL"

### ISSUE THREAD

**Issue by amotl** [samschott/desktop-notifier#49]
Dear Sam,

while we haven't worked on https://github.com/caronc/apprise/issues/742 yet, I wanted to humbly make you aware of a request submitted by @mobilelifeful at https://github.com/caronc/apprise/issues/786.

The [terminal-notifier](https://github.com/julienXX/terminal-notifier) program has a sweet feature to make the notification message clickable, by providing a target URL. Do you think this feature could also be added to `desktop-notifier` in any way?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Oh, I see that `desktop-notifier` is actually providing a callback into Python on behalf of the `on_clicked` hook. That's sweet! It should be easy to layer the "open URL" feature as a convenience thing on top.

**Comment by samschott** [comment]
In that case, I'll mark this as closed :)

**Comment by khurshid-alam** [comment]
@amotl @samschott Any short example for this ?
