### ISSUE TITLE
Crash on import 

### ISSUE THREAD

**Issue by KonstantinosPetrakis** [samschott/desktop-notifier#92]
* Desktop Notifier version: 3.5.4 (the latest in pypi right now)
* Python version: 3.10.6
* Operating System: Ubuntu 20.04

The library cannot be imported from a virtual environment using venv.  

I simply tried to:
```python
from desktop_notifier import DesktopNotifier
```

And got with this traceback:
```
Traceback (most recent call last):
  File "/home/kostas/programming/lyrics-app/main.py", line 4, in <module>
    from desktop_notifier import DesktopNotifier
  File "/home/kostas/programming/lyrics-app/env/lib/python3.10/site-packages/desktop_notifier/__init__.py", line 2, in <module>
    from .main import DesktopNotifier, Button, ReplyField, Notification, Urgency
  File "/home/kostas/programming/lyrics-app/env/lib/python3.10/site-packages/desktop_notifier/main.py", line 29, in <module>
    from .base import (
  File "/home/kostas/programming/lyrics-app/env/lib/python3.10/site-packages/desktop_notifier/base.py", line 22, in <module>
    from importlib_resources import path as resource_path
ImportError: cannot import name 'path' from 'importlib_resources' (/home/kostas/programming/lyrics-app/env/lib/python3.10/site-packages/importlib_resources/__init__.py
```

**Comment by KonstantinosPetrakis** [comment]
I found a fix, in desktop_notifier/base.py you have to replace:

```python
from importlib_resources import path as resource_path
```
with:
```python
try:
    from importlib.resources import path as resource_path
except ImportError:
    from importlib_resources import path as resource_path
```

I saw the correct use for supporting Python versions > 3.7 in this stackoverflow thread: 
https://stackoverflow.com/questions/58520128/how-to-use-importlib-resources-pathpackage-resource 

Please notify (hehe (project name)) me if you patch it so I pull it again from pypi. Thanks.

**Comment by ceamac** [comment]
> ```python
> try:
>     from importlib.resources import import files, as_file
> except ImportError:
>     from importlib_resources import import files, as_file
> ```

We don't have `importlib-resources` in Gentoo for Python 3.10+, it should not be needed.  Please reconsider applying this change.

Thank you!

**Comment by samschott** [comment]
Hrmp, the convenience of importlib_resources is that it provides a more uniform API across multiple Python releases.

**Comment by ceamac** [comment]
Thank you for the quick change and release!
