### ISSUE TITLE
Issue with request_autharization

### ISSUE THREAD

**Issue by KonstantinosPetrakis** [samschott/desktop-notifier#95]
* Desktop Notifier version: 3.5.6
* Python version: 3.11.1
* Operating System: Windows 11

### Description
I am trying to push a notification like this:

```python
notifier = DesktopNotifier("SyncLyrics", ICON_URL)
await notifier.send(title="SyncLyrics", message="wow")
```

But I get this error:
```
Traceback (most recent call last):
  File "C:\Users\Kostas\Desktop\Programming\SyncLyrics\sync_lyrics.py", line 122, in <module>
    asyncio.run(main())
  File "C:\Users\Kostas\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Kostas\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kostas\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Kostas\Desktop\Programming\SyncLyrics\sync_lyrics.py", line 105, in main
    await notifier.send(title="SyncLyrics", message=lyric)
  File "C:\Users\Kostas\Desktop\Programming\SyncLyrics\env\Lib\site-packages\desktop_notifier\main.py", line 317, in send   
    return await self.send_notification(notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kostas\Desktop\Programming\SyncLyrics\env\Lib\site-packages\desktop_notifier\main.py", line 223, in send_notification
    await self.request_authorisation()
  File "C:\Users\Kostas\Desktop\Programming\SyncLyrics\env\Lib\site-packages\desktop_notifier\main.py", line 203, in request_authorisation
    return await self._impl.request_authorisation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kostas\Desktop\Programming\SyncLyrics\env\Lib\site-packages\desktop_notifier\winrt.py", line 98, in request_authorisation
    return bool(self.notifier.setting == NotificationSetting.ENABLED)
                ^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -2147023728] Element not found
```

### What I Did
By the way I saw some related closed issues, maybe the issue (or a similar one) is back. Just adding a return statement on the top of request_authorisation (just avoiding to run the function) fixes the problem and notifications are pushed perfectly. 

```python
    async def request_authorisation(self) -> bool:
        """
        Requests authorisation to send user notifications. This will be automatically
        called for you when sending a notification for the first time. It also can be
        called manually to request authorisation in advance.

        On some platforms such as macOS and iOS, a prompt will be shown to the user
        when this method is called for the first time. This method does nothing on
        platforms where user authorisation is not required.

        :returns: Whether authorisation has been granted.
        """

        return # The holly statement that fixes everything
        with self._lock:
            self._did_request_authorisation = True
            return await self._impl.request_authorisation()
```

PS: 
I hope you don't hate me for finding issues every 5 days like I am a workaholic tester that has a beef with you.

**Comment by KonstantinosPetrakis** [comment]
Maybe you can add an if clause to check if the platform is not Windows and only then call request_authorization? I also own a computer with Windows 10 if you want me to check if it fails there too.

**Comment by iamkroot** [comment]
Getting the same error on Windows 10 
```
Edition	Windows 10 Pro
Version	22H2
OS build	19045.3448
```

Another hack to get it working is setting
```python
notifier._did_request_authorisation = True
```
before creating any notifications.

On a related note I'm wondering why we need authorization to send notification if it works without auth. Is this a Windows bug - are they not enforcing the auth? Or do bare python apps not need auth?

**Comment by iamkroot** [comment]
Update: This is most likely a Windows bug. Or we are setting the `app_id` incorrectly. Weird behaviour:
1. Try sending a notification. Get `ElementNotFound` as shown in issue description.
2. Now, bypass the `request_auth` altogether (using any of the hacks mentioned previously) and just send the notif. It is successful.
3. Here's the crucial part- even if we rollback the hack (restore original code as in step 1), we can still send notifications.

It seems to have something to do with the APP ID. As soon as I change the `app_id`, I hit the `ElementNotFound` error again in step 1 and 3. It disappears after doing step 2. The very act of sending a notification fixes the bug.
I am not sure if the fix persists even across restarts.

**Comment by samschott** [comment]
> On a related note I'm wondering why we need authorization to send notification if it works without auth. Is this a Windows bug - are they not enforcing the auth? Or do bare python apps not need auth?


While Windows does not currently allow promoting the user for authorization to send desktop notifications, it does allow the user to disable desktop notifications for individual apps.

In `desktop-notifier`, the contract API of `request_authorization()` is that it will request authorization if possible, and return whether the app is allowed to send notifications. The latter at least can be done on Windows, therefore the check.

Could you also report which version of `winsdk` you have installed? On my local virtual machine, everything is working as expected, so I am a bit confused by this report.

**Comment by iamkroot** [comment]
> Could you also report which version of `winsdk` you have installed? On my local virtual machine, everything is working as expected, so I am a bit confused by this report.

Ah about that- I was unable to get `winsdk==1.0.0b9` install on my machine. I had to use `1.0.0b10` from #100. I see from winsdk changelog that they added support for some newer windows versions 22H2- maybe your VM is outdated?

**Comment by samschott** [comment]
v1.0.0b10 should also work fine, AFAIK there are not backward incompatible changes which would affect `desktop-notifier`. I've just been pinning the version until its out of beta and there is a stable release.

**Comment by samschott** [comment]
And according to the API docs, `ToastNotifier.Setting` should also be present on the report OS build 19045.

**Comment by iamkroot** [comment]
Yes, it is. I did a `dir(self.notifier)` right after it is created, and the `setting` attribute _is_ present there. Considering that it is a property, I'm guessing the exception is somewhere inside winsdk/winrt when we call the getter.

**Comment by iamkroot** [comment]
As mentioned before, we don't get the exception after we have sent at least one notification with that app id. Seems like sending a notif populates some internal data structures only after which `self.notifier.setting` is valid.

**Comment by AuroraWright** [comment]
I looked into this and this seems to be what's happening:
>>> notifier = DesktopNotifier(app_name='RANDOM')
by itself, this just creates HKEY_CURRENT_USER\Software\Classes\AppUserModelId\RANDOM (desktop-notifier itself does it)
>>> notifier.send_sync(title="Hello world!", message="Sent from Python")
this creates keys in:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PushNotifications\Backup\
and also seems to create entries in the database here:
C:\Users\xxx\AppData\Local\Microsoft\Windows\Notifications
however, due to a bug in Windows or in the Python SDK (???) it returns an OSError
the "C:\Users\xxx\AppData\Local\Microsoft\Windows\Notifications" bit is what triggers this apparently. If you stop the services and delete those files the error will happen again once while it creates the entries.
On subsequent notifications, everything works fine since the entries were already created.

I think it would make sense to add an exception for OSError and consider it as authenticated (for the very first notification)

**Comment by samschott** [comment]
Thanks for digging this up! So I assume its the following statement that causes the exception?
```Python
self.notifier.setting == NotificationSetting.ENABLED
```
I'll try to reproduce it locally after deleting the corresponding files.

**Comment by AuroraWright** [comment]
> Thanks for digging this up! So I assume its the following statement that causes the exception?
> 
> ```python
> self.notifier.setting == NotificationSetting.ENABLED
> ```
> 
> I'll try to reproduce it locally after deleting the corresponding files.

Yes, that's correct

**Comment by samschott** [comment]
Sorry, yeah, the original report already said that this triggers the exception. What I meant to ask: Is it this statement that triggers changes to `C:\Users\xxx\AppData\Local\Microsoft\Windows\Notifications`?

**Comment by AuroraWright** [comment]
> Sorry, yeah, the original report already said that this triggers the exception. What I meant to ask: Is it this statement that triggers changes to `C:\Users\xxx\AppData\Local\Microsoft\Windows\Notifications`?

I'm actually not sure since I didn't track it down that far but I think it's likely when it sends the notification itself in the sdk

**Comment by AuroraWright** [comment]
In my program I just added an asyncio.run for DesktopNotifier.request_authorisation() (where I "pass" OSError) on program startup, I removed the AppData\Local\Microsoft\Windows\Notifications folder and it never triggered the error
